// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'copy': string;
  'image': string;
  'infoKey': string;
  'json': string;
  'modalContent': string;
  'modalContentRow': string;
  'pre': string;
}
export const cssExports: CssExports;
export default cssExports;
