// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bold': string;
  'bottomButton': string;
  'buttonFull': string;
  'contentContainer': string;
  'copy': string;
  'filter': string;
  'filterClear': string;
  'filterContainer': string;
  'filtersPanel': string;
  'gray': string;
  'image': string;
  'infoKey': string;
  'json': string;
  'modalContent': string;
  'modalContentRow': string;
  'nowrap': string;
  'pre': string;
  'spinner': string;
  'table': string;
  'tableContainer': string;
  'tablePlaceholder': string;
}
export const cssExports: CssExports;
export default cssExports;
