// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'authContainer': string;
  'bold': string;
  'bottomButton': string;
  'buttonFull': string;
  'contentContainer': string;
  'errorMessage': string;
  'errorStatus': string;
  'filter': string;
  'filterClear': string;
  'filterContainer': string;
  'filtersPanel': string;
  'gray': string;
  'logo': string;
  'nowrap': string;
  'spinner': string;
  'tableContainer': string;
  'tablePlaceholder': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
